name: CI

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build PC-2019.3.3
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=PC-2019.3.3
    - name: Test PC-2019.3.3
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=PC-2019.3.3
    - name: Build PC-201.5616-EAP-CANDIDATE-SNAPSHOT
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=PC-201.5616-EAP-CANDIDATE-SNAPSHOT
    - name: Test 201.5616-EAP-CANDIDATE-SNAPSHOT
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=PC-201.5616-EAP-CANDIDATE-SNAPSHOT

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: jacocoTestReport -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=PC-2019.3.3
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}