name: CI

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pycharm-version: ['2023.1.2', '2023.2']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=${{ matrix.pycharm-version }}
