name: CI

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pycharm-version: ['PC-2019.3.3', '201.5616-EAP-CANDIDATE-SNAPSHOT']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Test
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=$VERSION
      env:
        VERSION: ${{ matrix.pycharm-version }}
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: jacocoTestReport -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=PC-2019.3.3
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}