name: "Verify plugin"

on:
  schedule:
    - cron: "32 22 * * 1"

jobs:
  coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: runPluginVerifier -PintellijPublishToken=FAKE_TOKEN -PintellijVersion=2022.3
